export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

export const ADD_NEW_SUBJECT = 'ADD_NEW_SUBJECT';
export const GET_ALL_SUBJECTS = 'GET_ALL_SUBJECTS';

export const ADD_NEW_LEVEL = 'ADD_NEW_LEVEL';
export const GET_ALL_LEVELS = 'GET_ALL_LEVELS';

export const ADD_NEW_MEDIUM = 'ADD_NEW_MEDIUM';
export const GET_ALL_MEDIUMS = 'GET_ALL_MEDIUMS';